export const WILDLIFE_SUGGESTIONS: string[] = [
  "australian brushturkey",
  "agile antechinus",
  "cattle",
  "bush thick-knee",
  "dingo",
  "pacific emerald dove",
  "grey shrikethrush",
  "white-winged chough",
  "laughing kookaburra",
  "fallow deer",
  "eastern yellow robin",
  "domestic cat",
  "bar-shouldered dove",
  "australian magpie",
  "human",
  "northern brown bandicoot",
  "european hare",
  "eastern gray kangaroo",
  "superb lyrebird",
  "house mouse",
  "european rabbit",
  "long-nosed bandicoot",
  "noisy pitta",
  "rattus",
  "australian bush rat",
  "black rat",
  "pied currawong",
  "wild boar",
  "australian echidna",
  "red-legged pademelon",
  "short-eared possum",
  "mountain brushtail opossum",
  "common brushtail",
  "lace monitor",
  "common wombat",
  "red fox",
  "swamp wallaby",
  "domestic goat",
  "southern cassowary",
  "grey-headed robin",
  "musky rat kangaroo",
  "orange-footed scrubfowl",
  "red-necked wallaby",
  "northern chowchilla",
  "giant white-tailed rat"
]
